### ISSUE TITLE
Determine general page layout

### ISSUE THREAD

**Issue by azmtbr** [azmtbr/rescue-site#1]
As a user, I want a clean and visual landing page that will help me to quickly determine where I need to navigate to on the page.

**Comment by azmtbr** [comment]
![rescue site landing page](https://cloud.githubusercontent.com/assets/13734584/13240584/fbc54524-d9a0-11e5-9f99-401e07f2369b.jpg)

**Comment by matstc** [comment]
Usually I would worry about the navigation as part of each individual story. (Unless you have very specific navigation requirements).
