### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by azmtbr** [azmtbr/rescue-site#3]
1.  As a user, I want to be able to fill out a contact form that will send an email to the rescue       with a message/question that I write. (2)
       - This will require a link to a form modal on each animals’ page. 
       - Services like SendGrid or Nodemailer can be utilized to send emails containing              the information that is filled out in the form.

**Comment by azmtbr** [comment]
Will be very similar to adoption form but with different fields. 
[adoption form issue](https://github.com/azmtbr/rescue-site/issues/5)

**Comment by azmtbr** [comment]
@matstc 
-I was able to get the email to send, but the parameters from the frontend aren't in there. 
-I they are being sent as params when I send the form so I know that they are going somewhere, I'm just not sure how to get them to show in the view. 

```
Started POST "/api/rescues/1/contacts" for 127.0.0.1 at 2016-03-03 16:18:02 -0700
Processing by ContactsController#create as JSON
  Parameters: {"name"=>"Koni", "email"=>"email@email.com", "message"=>"Koni", "rescue_id"=>"1"}
  Rendered contact/send_contact_form.html.erb within layouts/mailer (0.1ms)

Contact#send_contact_form: processed outbound mail in 9.5ms

Sent mail to monkeydogphotography@gmail.com (583.1ms)
Date: Thu, 03 Mar 2016 16:18:02 -0700
From: contact@rescuesite.com
To: monkeydogphotography@gmail.com
Message-ID: <56d8c62a70628_f1c3ffe742c63b83174f@MacBook-Pro.local.mail>
Subject: Contact form from website
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>From:</h3>
    <p> name </p>
    <h3>Email:</h3>
    <p> This should be the email </p>
    <h3>Message:</h3>
    <p> This should be the message </p>
  </body>
</html>
```

Here's the applicable commit from the api:
[Here it is](https://github.com/azmtbr/rescuesite-api/commit/4dc8154dd7f6736ab96ceb129255c71aa428aa3b)

**Comment by matstc** [comment]
Hi Jon. Very good! The info from the params needs to be retrieved using the normal syntax of `params[:email]` or `params[:message]`.

Also, there was an extra colon in the mailer which I now removed.

The next step would be to look at the rescue id parameter and to make sure to send the email to the right rescue. That probably entails adding an email address on the rescue model.

**Comment by azmtbr** [comment]
@matstc 
-Contact form working well now, thanks!
-I added email to the rescue model and added it to the rescue migration, but first wanted to finish friendly_id.
-Working on adding friendly_id. I was able to give both the rescue and animal their own slugs for their respective names. However, when I click on the name in the listing view, the URL becomes capitalized. When I manually change it to lowercase, the profile page displays normally. I thought that this being in there would solve that issue:

```
def set_animal
      @animal = Animal.all.find  {|a| a.name.downcase == params[:id]}
 end
```

I've tried to make the animal name lowercase in a few spots including in the Restangular request on the frontend. I've put `.parameterize` or `.normalize` on everything I could find to no success. 

I'll be working on identifying the rescue both in the view and for the contact form next since the `:rescue_id` is now hardcoded in the restangular request.

**Comment by matstc** [comment]
Hi Jon. A few notes: usually, you would want the URL to always be lower case (e.g. `/animals/caramel`). And the `set_animal` method should really be using friendly_id's finder:

``` ruby
def set_animal
  @animal = Animal.friendly.find(params[:id])
end
```

And when you construct the URL, you want to use the friendly id (i.e. `slugged`) instead of the id.

**Comment by azmtbr** [comment]
@matstc 
-finished contact form functionality. Starting on Adoption form now. 
[this commit](https://github.com/azmtbr/rescue-site/commit/51e681d596068687f7703b7cdce4a285601e95cb)

-Should I be worrying about styling these pages now or just the functionality?

**Comment by matstc** [comment]
@azmtbr I wouldn't worry about the styling for now although you should make sure that things are useable and make sense from a UX perspective. You want to think enough about UX so that you won't be surprised by the amount of work left to do later on.

**Comment by azmtbr** [comment]
@matstc 
-did some basic styling after completing the adoption form functionality
