### ISSUE TITLE
Admin area

### ISSUE THREAD

**Issue by azmtbr** [azmtbr/rescue-site#8]
1.  As an admin, I want to be able to edit text and images on the site without the help of the      developer (4)
       - Implement a cms or create an admin area of the site. 
               -add authentication to access this area of the site.

**Comment by matstc** [comment]
Having an admin area feels like the easiest option. How will admins be able to edit the content? And what specific fields or images will they be able to modify?

**Comment by azmtbr** [comment]
It seems like something like ng-admin will work as an admin area. [ng-admin](https://github.com/marmelab/ng-admin)

It obviously wouldn't allow anyone to change the layout of the site as far as galleries or even the order of the images in the galleries are concerned. But, they will be able to add/remove images of the animals and change the bio and stats for the animals. It would also allow them to add/update events in the events section. 

I also found something called loopback-angular-admin
[loopback](https://github.com/beeman/loopback-angular-admin)

**Comment by matstc** [comment]
Very good. Are you planning on using a Loopback API? Or perhaps using Rails?

**Comment by azmtbr** [comment]
@matstc 

Ok, starting in on this now. So far I'm somewhat following what I did in the rails course with bloccit. I've only worked on the api and plan on trying to create users using the frontend tomorrow. 

So far I've created a User model and controller, and a Sessions model and controller, and some other things. I linked the user to a rescue as everything else is. If you have time to at least let me know if I'm on a viable track that would be great. Or else I'll just jump off this train. lol

Here are the relevant commits:

[api commit 1](https://github.com/azmtbr/rescuesite-api/commit/5b523d32791d7376240f898cc333656e28199480)

[api commit 2](https://github.com/azmtbr/rescuesite-api/commit/db324ee8b9fa793a6fa0353e21c73da5598a1870)

**Comment by matstc** [comment]
Hi Jon. That looks good in general. Although there seems to be a typo in the session helper:

```
User.find_by(:id session[:user_id])
```

Also, you might want to avoid using sessions at all since you're building an API. Make sure to watch [this Railscast](http://railscasts.com/episodes/352-securing-an-api?view=asciicast) on securing an API. You could do it manually. If you choose to use devise, the token auth module has been taken out. Perhaps a gem [like this one](https://github.com/baschtl/devise-token_authenticatable) would save you a bit of work.

There's a bit of confusion online as to how to secure an API but conceptually it's very simple. The first API request sends out username + password and receives a token. All subsequent requests need to send back that token (until the token expires in which case username + password need to be sent anew).

**Comment by azmtbr** [comment]
@matstc 

I'm able to sign a user in on the frontend, but the user doesn't persist.
When I try to delete, I get:
![screen shot 2016-03-28 at 8 54 15 pm](https://cloud.githubusercontent.com/assets/13734584/14097561/441b112c-f527-11e5-8f67-9ebea86bccb8.png)

The response headers for the delete action aren't showing any of the required info. 

I am able to destroy a user using Postman as we did today. So, I know the routes are ok and I'm asking for the right data. 

Should I be using cookies to store the client and other header info in the browser?
 [api commit](https://github.com/azmtbr/rescuesite-api/commit/8a73083f3ac925a566389494560423e30a62ec1c)

[frontend commit](https://github.com/azmtbr/rescue-site/commit/278b9ebddd9431eb725b3fa8a49f048543ad5e70)

**Comment by azmtbr** [comment]
@matstc 

It turns out I had a typo in `application.rb` relating to `rack-cors`.

[fix commit](https://github.com/azmtbr/rescuesite-api/commit/958ddb40a0b0a34b36d05ffa9479831dc7cb0d62)

So sign in and out is working somewhat now. I can sign in/out as long as I don't leave the app. When I refresh the page, the `client` stays the same, but the `access-token` changes causing validation to fail. This is strange and I'm digging into it now. 

Will now be working on some UX things and cleaning things up a bit if I can get this issue fixed.

**Comment by matstc** [comment]
Very good Jon. Did you figure out the problem with the access token on refresh?

**Comment by azmtbr** [comment]
I did not.
It's almost like it starts a new session when the page is refreshed, but doesn't log the user in. From what I read in the docs, the default token expire time is 2 weeks. Strange.

 I did some more research but had to stop for the day. I'll get on it tomorrow morning and will hopefully be able to find a solution.

**Comment by matstc** [comment]
@azmtbr Your users are still signed in when they refresh but the UI doesn't take that into account. So it looks like you're not signed in but you really are. Here's some console output as an example:

![signed-in](https://cloud.githubusercontent.com/assets/58882/14172863/c443bf60-f73a-11e5-91db-789c75ca5dab.png)

The gist of it is: if you call `$auth.validateUser()`, you will get a promise and from that promise you can get the current user. Then you can refresh your user object on the scope so that the UI will react to the current user.

You're very close!

**Comment by azmtbr** [comment]
@matstc 

And just when we thought this was closed.

 It turns out that `angular-file-upload` does, in fact, have an issue with the user validation. The `FileUploader` needs custom headers containing the same info that `ng-token-auth` automatically asks for. I know how to get the `token-type` and the `uid`, but am not sure how to get a hold of `access-token`, `expiry`, and `client`. 

```
$scope.galleryUploader = new FileUploader({url: "http://127.0.0.1:4000/api/rescues/$RESCUE_ID/galleries/" + animal.gallery_id + "/photos",
                                            method: 'POST',
                                            alias: "photo[gallery_image]",
                                            withCredentials: true,
                                            headers: {
                                                      // 'access-token': $rootScope.user.token,
                                                      // 'expiry': $rootScope.user.expiry,
                                                      'token-type': 'Bearer',
                                                      'uid': $rootScope.user.email,
                                                      // 'client': $rootScope.user.client_id
                                                    }
                                            });
```

The commented out parts of the `headers:` object return `undefined`. 

![screen shot 2016-03-31 at 8 20 20 pm](https://cloud.githubusercontent.com/assets/13734584/14196955/2933ad16-f77e-11e5-9c72-22f1b9cd6eb1.png)

**Comment by matstc** [comment]
@azmtbr According to the [ng-token-auth docs](https://github.com/lynndylanhurley/ng-token-auth#angular-file-upload), you can pass in the headers manually like so:

```
        headers: $auth.retrieveData('auth_headers')
```

That worked well for me and I pushed that fix. I also pushed a small commit for the api repo to make sure the actions require authentication.

**Comment by azmtbr** [comment]
@matstc 

Unfortunately, this is a problem that I've been running into lately with `angular-file-upload`. People call more than one angular uploader "`angular-file-upload`".

The link in the  [ng-token-auth docs](https://github.com/lynndylanhurley/ng-token-auth#angular-file-upload), while it says `angular-file-upload`, actually takes you to the `ng-file-upload` github page. I think that this solution is for that particular uploader. 

This is all that I get from the [angular-file-upload docs](https://github.com/nervgh/angular-file-upload/wiki/Module-API#properties):
`headers {Object}: Headers to be sent along with the files. HTML5 browsers only.`

Having said that, this kind of still works. I say kind of because it lets me upload an image while signed in, but only one. If I try to upload a second image, and it doesn't matter which uploader I'm using, I get an unauthorized error. It's like it works on the first instance of `FileUploader` only. 

Also, the user is signed out after the first upload. 

Very strange I think. I do remember seeing this in my searching, but once I realized that it was for `ng-file-upload`, I passed it by. I probably should have looked at this a little longer. 

I'll keep digging.

Also, I sent the bullet-point list about the app in production to you as a message on bloc just FYI.

**Comment by matstc** [comment]
Oh I see. That's confusing. It's probably not working twice because the access token is not refreshed… 

What I would do is:
1. Make sure there is no documented way of taking control of the headers and making it work with file uploads.
2. Check the 4 headers (in the request and the response) when a file is successfully uploaded and then check them again in the subsequent request to the server. I am assuming the access token is not getting refreshed.
3. Take (more) control of the ajax handling to forcefully refresh the access token.
4. If all else fails: switch to the other file upload module.

Let me know how it goes.

**Comment by azmtbr** [comment]
@matstc 

After spending a morning on 1-3, I ended up going with choice 4. lol

I was able to get `ng-file-upload` working well with the single profile image upload. The token validation issue is no longer an issue. However, it's not working with the gallery uploader. It's giving me this error:
`param is missing or the value is empty: photo`
refering to line 70 in `photos_controller.rb`:

```
      params.require(:photo).permit(:gallery_image)
```

New gallery uploader:
If you look at the actual commit, there is some more code that I meant to comment out before committing but didn't save. That code didn't fix the issue anyway. 

```
  $scope.galleryPicUpload = function (files) {
            Upload.upload({
                url: "http://127.0.0.1:4000/api/rescues/$RESCUE_ID/galleries/" + animal.gallery_id + "/photos",
                headers: $auth.retrieveData('auth_headers'),
                method: 'POST',
                fileFormDataName : photos,
                file: files
...
```

The main problem is how to reference the `:photo`. From what I can find out, we can't use `alias: 'photo[gallery_image]'` like last time but there must be another way. 

html just in case:

```
<input type="file" ngf-select ng-model="files" name="files" ngf-pattern="'image/*'"
      ngf-accept="'image/*'" ngf-max-size="20MB" ngf-multiple="true"></input>
```

[Here's the full commit](https://github.com/azmtbr/rescue-site/commit/98f001450318c12b5ad17909833d8514a2bb457c)

**Comment by matstc** [comment]
All right. That works too... I pushed a fix that uses the `data` key to rename the request parameters. That made it work. Give it a try and let me know if that works for you.

**Comment by azmtbr** [comment]
Works perfectly and makes sense! Thanks. Now to erase all evidence of the old uploader and clean up that page a bit.
